spring:
  application:
    name: MEMBER
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2
    addresses: amqps://b-f96775a8-8bcb-4e8f-a88d-f5e27cb54f03.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!
  datasource:
    driver-class-name: org.postgresql.Driver   #postgresql
    url: jdbc:postgresql://database-1.cmu99dhdrulc.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace

    username: postgres
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

---
#spring:
#  profiles: MEMBER
spring:
  application:
    name: MEMBER
    cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://ec2-13-125-152-179.ap-northeast-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: ec2-3-36-96-181.ap-northeast-2.compute.amazonaws.com
management:
  endpoints:
    web:
      exposure:
        include: "*"